### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by cyouh95** [CrystalCo/Jammming#1]
Since everyone's access token should be different, make sure not to hard code yours into **Spotify.js**. Just declare the variable:
```js
let accessToken;
```
https://github.com/CrystalCo/Jammming/blob/master/src/util/Spotify.js#L4

Then, your `.getAccessToken()` method will set the value. Make sure to also remove the `let` in this line, as you want to set the value of the above declared variable and not create a new one within the scope of this method:
```js
accessToken = accessTokenMatch[1];
```
https://github.com/CrystalCo/Jammming/blob/master/src/util/Spotify.js#L25

**Comment by CrystalCo** [comment]
Updated syntax in Spotify.js to `let accessToken;` and removed "let" from the accessToken in the `.getAccessToken()` method.
