### ISSUE TITLE
Saving Playlist

### ISSUE THREAD

**Issue by cyouh95** [CrystalCo/Jammming#5]
The playlist name you'd want to pass to your `Spotify.savePlaylist()` method should be the one stored in your **App** component's state:

```js
Spotify.savePlaylist(this.state.playlistName, trackURIs);
```
https://github.com/CrystalCo/Jammming/blob/master/src/components/App/App.js#L63

Currently, you're trying to use the `playlistName` passed in as parameter to your `.savePlaylist()` method, but you were not passing anything to this method in **Playlist.js**.

https://github.com/CrystalCo/Jammming/blob/master/src/components/App/App.js#L58
https://github.com/CrystalCo/Jammming/blob/master/src/components/App/App.js#L83
https://github.com/CrystalCo/Jammming/blob/master/src/components/Playlist/Playlist.js#L24

**Comment by CrystalCo** [comment]
saveplaylist method is now updated.  Removed the playlistName from .savePlaylist() method's parameter, updated the Spotify.savePlaylist parameter to "this.state.playlistName", and reformatted the "this.setState" to follow after the Spotify.savePlaylist using .then().
